development:
  adapter: postgresql
  encoding: unicode
  database: blog_development
  pool: 5
  username: vova

test: &test
  adapter: postgresql
  encoding: unicode
  database: blog_test
  pool: 5
  username: vova
cucumber:
  <<: *test
